### ISSUE TITLE
GPS altitude in end of flight stats?

### ISSUE THREAD

**Issue by jaffadog** [ShikOfTheRa/scarab-osd#134]
I know it's possible to display either or both baro and gps altitude in the OSD.  It looks like the end of flight stats page displays maximum baro altitude.  Is it possible to display maximum gps altitude instead?  thanks!

**Comment by ShikOfTheRa** [comment]
it would require some code changes for that. certainly possible

**Comment by ShikOfTheRa** [comment]
As an fyi, if select FIXEDWING, the OSD uses GPS  instead of BARO / MAG. Can then re-enable the MAG and it will be close to what tyou want (unless you want to see both baro and GPS and same tiem... 
#define USEMAGHEADING             // Undefine this to use MAG for FW heading instead of GPS (requires controller with MAG sensor) 

possibly:
//#define DISABLEGPSALTITUDERESET   // Disables automatic reset of GPS Altitude to zero at arm for FC that already provide this functionality. 

Added to the wish list anyway. Its not too bad so probably will be done in next release or 2

**Comment by ShikOfTheRa** [comment]
Closing as on teh wishlist.
