### ISSUE TITLE
OSD + Bluetooth

### ISSUE THREAD

**Issue by Baatezu** [ShikOfTheRa/scarab-osd#144]
![1](https://cloud.githubusercontent.com/assets/13260083/11296552/d325673c-8f83-11e5-8d55-77d9a8c755d0.jpg)
MWOSD 1.5 (minimOSD) can work on Flip32 (cleanglight 1.10.0) like show on this pictures.
Waht need to commit on conf.h?
Or it's not possible?

**Comment by nathantsoi** [comment]
I've never been able to get this to work. I think the bluetooth module and the OSD are both trying to send MultiWii serial protocol commands. If we could disconnect the MWOSD TX line, it might work, but I think this would make the OSD inoperable, since it must request the data it wants. Perhaps we could change CleanFlight to auto-send OSD info on a given port or change MWOSD to accept blackbox data :)

**Comment by lichtl** [comment]
I think as stated in there you need to have either the Bluetooth TX or OSD TX being disconnected. I'm not 100% sure but I think the OSD should even work with only RX (however I believe it then won't allow you to perform pid/config changes using the OSD

**Comment by Baatezu** [comment]
When a disconnect TX on OSD, OSD say NO DATA.

Try later recomendation @nathantsoi

**Comment by dustin** [comment]
@lichtl the OSD requests data from the flight controller to display.  The flight controller doesn't just broadcast its state..

I don't see an MWOSD bug here.

**Comment by tracernz** [comment]
@dustin It can using MSP telemetry, but looks like CF will remove that anyway cleanflight/cleanflight#1106.

**Comment by dustin** [comment]
I'd assume you could share the (FC-side) tx pin and have it somewhat work if bluetooth is actually asking for stuff.  Seems like a bunch of work, though.  I guess a hardware MSP mux would also do it.  But just putting it on a different UART is the easiest approach.

**Comment by ShikOfTheRa** [comment]
What is said above should cover everything
