### ISSUE TITLE
Display PIDs while flying

### ISSUE THREAD

**Issue by KevinVecchione** [ShikOfTheRa/scarab-osd#179]
It would be nice to get visual confirmation of PID for R/P/Y while tuning with Cleanflight adjustment switches during flight. Is something like this theoretically possible? I'm open to helping out and contributing this to the code if someone can give me a quick orientation of what's what in the source.

Thanks!

**Comment by ShikOfTheRa** [comment]
This is definitely possible.
I can add to the wish list however, not recommended as a permanent option and low on priority list. Mainly because...
1 adds processing time for serial for both the FC and the OSD. Everything else will slow down.
2 lack of code space. if anyone implements, bust be able to be excluded with #define

**Comment by ShikOfTheRa** [comment]
Have no short term plans to implement. Have added to the roadmap "wishlist" for someone to implement if they desire.
