### ISSUE TITLE
Support S.Port telemetry

### ISSUE THREAD

**Issue by rtieland** [ShikOfTheRa/scarab-osd#246]
It would be nice if we could use S.Port for telemetry.

**Comment by ShikOfTheRa** [comment]
I have no idea what you are requesting - not being an S port user... could you elaborate

**Comment by barthalamu** [comment]
I'm not sure what he's thinking, but I've been pondering the idea of using the SmartPort output from my Taranis and send it to a local OSD connected to my goggles.

Since any data I care to recieve (volts, Amps, mAh, RSSI) is sent as telemetry anyway, it would free up a serial port, save some space and weight on the craft, and make the build a little cleaner. You could also use it to monitor your ground station battery and if your FPV feed is being broadcast, streamed, or otherwise sent elsewhere, you could send a clean uncluttered picture and only you would have the OSD info that you need.

I could also see eventual possibilities of getting other feedback from and/or control of your ground station, like VRX RSSI, diversity channel selection, lap times sent from a timing system, maybe even control of the VRX itself to change channels.

**Comment by axyspg** [comment]
I think that it's similar to the idea I've posted on my blog. You can check it at:

http://someonedidthatalready.blogspot.com.es/2015/12/how-to-save-uart-port-on-your-msp.html

The idea is to free a serial port and send SmartPort telemetry using MSP data from MWOSD.

**Comment by ShikOfTheRa** [comment]
Nice project ^^

I am going to close this as its not going to be developed. Sorry
