### ISSUE TITLE
Support for Raceflight

### ISSUE THREAD

**Issue by ShikOfTheRa** [ShikOfTheRa/scarab-osd#313]
#1 - please keep this thread clean. No bitching.

Any RF users - please advise what issues are running RF. WHat works / what doesn't / Any request for OSD menu configuration

**Comment by proggod** [comment]
From what I understand they sniffed the packets rf sent and all looked fine with Msp, so they didn't know why the osd didn't recognize.

**Comment by dustin** [comment]
This one sentence answers *so* many questions from the last couple weeks of #301, but leaves a few more.  Starting with what we know:

* RaceFlight is using MSP.
* Requests from MWOSD to MSP are (possibly) understood.
* Responses are possibly not understood or incomplete.

What we still don't know:

* How is MWOSD built?
* How is MWOSD configured?
* What does the user expect to be on the screen?
* What is on the screen?

There are two classes of possibilities for what's wrong:

* The user has misconfigured MWOSD.
* RaceFlight is not sending correct or sufficient responses.

If we assume the user has configured MWOSD incorrectly then we don't have enough information to say MWOSD doesn't support RaceFlight and this bug should be closed until we do.

So that leaves us assuming that RaceFlight isn't doing the right thing.

It sounds like MSP conversation has been captured between MWOSD and RaceFlight.  It would be trivial for someone here to tell you what RaceFlight is doing wrong if you attached it to the bug since we (at least I) know what MWOSD wants and have tons of tools for inspecting traces since I've made this stuff work on several systems with different providers and consumers.

Otherwise, there's not much we can do.

**Comment by jflyper** [comment]
In that case, I suspect the MSP packet being longer than UART receive buffer, or MSP reassembly buffer. The former is interrupt driven, and is checked for availability quite often, so it is less likely. The latter is more likely, which is 150 bytes long. I know it would overflow if fully loaded BOXNAMES is sent.

**Comment by ShikOfTheRa** [comment]
Could be right on length - there is a check for MSP size so it should drop and not overflow... but it will not process. Unlikely BOXNAMES - isn't enabled by default. 

I'll install raceflight this weekend and see for myself...

I've registered and couldn't see anywhere to get the latest therefore presume the one on chrome store is latest supported release.

**Comment by jflyper** [comment]
Yeah, right. Longer-than-buffer messages are detected and dropped upon message length checking.

**Comment by proggod** [comment]
The latest is on raceflight.net just register and go to downloads to get it.   If there is an issue you need us to fix on my end let me know.   We plan to replace all the MSP stuff in the next couple weeks with our new core, so it would be nice to know about any issues that make it less compatible.

**Comment by proggod** [comment]
And don't use the chrome store version, it will be updated this week, but its very out of date

**Comment by ShikOfTheRa** [comment]
Spent hours on the weekend and I just can't get it loaded onto a board using the one on the chrome store even with bootloader shorted. Weird because CF and BF both go ok.
I guess that was wasted effort anyway if its old.

Issue is I can't install it from the download link ( is that just added because I couldn't find it on weekend?)
You should be aware that many organisations block apps from non trusted sources. ie. I can only load from official store or unpacked extension...

**Comment by ShikOfTheRa** [comment]
Are you making the source public?

**Comment by proggod** [comment]
We have done a complete rewrite of the software, so that is why the new builds are on raceflight.net, eventually most source will be released, however there will be a few parts distributed in library format.   The configurator should load just fine, open up settings/extensions and drag it in.  We plan to update chrome store this week, but right now we are concentrating on beta releases, so we didn't want to do this till we release an official release.    Not to open a can of worms, but if you jumped onto what we use for support, i would have had you up and running in about 2 minutes :)   raceflightinfo.com has a guide on how to do it.

**Comment by ShikOfTheRa** [comment]
Ill shout on slack a bit later. Chrome doesn't permit a drag / drop option. Assume this comes as part of the usual corp policy controls to protect us stupid users... :(

**Comment by ShikOfTheRa** [comment]
OK its up and ruunning thanks to one of the guys. 
BTW, I thought raceflightinfo.com was the RF site - spent ages looking for download on wrong site! And it wasn't just me!! Suggest add a link to the main site. for idiots like us ! Might be obvious to you  but as someone who hasn't used it before....

**Comment by proggod** [comment]
Ya we know about the issue, we are going to change github, google, all our sites, etc to point to all the right places this week, our small beta testing group has turned into being the one of the biggest market share in racing software pretty quickly, so we are still playing catchup.  We had 35% at multigp nats, and a lot more have switched since then :)

**Comment by ShikOfTheRa** [comment]
So uploaded the RF bin using configuration and can't communicate with it any more :( even the bootloader pins sorted don't seem to let it recover. Weird. Cant even load CF ow either. Crap cos it was my only f3 board.. Don't suppose it would run enough on an f1 board to carry out testing either. Prob lock up. grrr

**Comment by dustin** [comment]
Two points of interest from earlier in the bug:

1. They claim to already have a trace.  It would be kind if they worked
with us some.
2. They claim to be rewriting all that anyway, so if you figured out what
was wrong with the existing code, it's likely to be broken again real soon
now.

**Comment by ShikOfTheRa** [comment]
I had a thought and just googled Raceflight OSD and there are a few posts showing Raceflight running with MWOSD.
I don't know versions, but it looks like its working for some at least.... couple of examples. Some are uploaded in last few weeks so assume fairly recent. 

https://www.youtube.com/watch?v=iwsK417Ak00

https://www.youtube.com/watch?v=IohVQIL6-lg
https://www.youtube.com/watch?v=frpd0JghvTY

**Comment by RBeaubien** [comment]
I have a Raceflight board on its way and I will do some thorough testing for you.

**Comment by jflyper** [comment]
@RBeaubien Looking forward to hearing the result.

@Channel
I've heard that RF is coming out with RF PDB+OSD+VTX or something similar.

**Comment by ShikOfTheRa** [comment]
So I tried raceflight today as seems like near zero interest in last xx months

The PID config seems to work. I have no idea if what is on OSD matches what real PID is in FC
Other like advanced do not. Looks like different params.
Horizon works
Modes are different in configurator so presume some differences there.

So I am going to remove all config options except PID and add it into list of supported FC, but with caveat of untested..

It is impossible to support from my side only. I'd love it to support raceflight but someone will else will have to amend MSP settings modes as appropriate.

Closing as not going to do any more
