### ISSUE TITLE
Betaflight / MWOSD CMS co-existance

### ISSUE THREAD

**Issue by ShikOfTheRa** [ShikOfTheRa/scarab-osd#364]
@jflyper 

Jflyper has added CMS support to some FC such as betaflight. 
This provides ability to access / configure all settings.

They can potentially clash in certain scenarios. This issue is to discuss and propose solutions. 

Potential options:

1:
in serial.ino:

if (armed || fontMode || configMode)  // change to: 
if (armed || fontMode )

case 0: // Enter / hold canvas mode
  if (configMode)
    configExit() // add this line to exit MWOSD config menu without saving
  canvasMode = true;
  break;

not sure if also need, in mwosd.ino:

if (canvasMode = true) configMode=0;

Question - is it possible to initiate canvas mode from OSD? that would be great to add into MWOSD menu

**Comment by ShikOfTheRa** [comment]
Actually I think just before the serial canvas case statement would work better. I'll submit a PR and try out tonight.

**Comment by ShikOfTheRa** [comment]
Er. dull question - how do you enter CMS mode on the FC ?! I can't find...

**Comment by skaman82** [comment]
if you mean the stick combo: yaw left+thr mid and pitch up

**Comment by ShikOfTheRa** [comment]
Brill. Have updated the main repository. Can't wait to try this out tonight!

**Comment by ShikOfTheRa** [comment]
Do you have to do soemthing to enable it - or is only ther ein F3 targets? Doesn't seem to obe initiation on my naze running bf 3.1

**Comment by skaman82** [comment]
Dunno about F1 targets I just needed to enable canvas in MWOSD and then it worked perfectly. Have no F1 target anymore to test...

**Comment by jflyper** [comment]
Ah, F1 targets drops CMS. Must be >128K targets.

**Comment by ShikOfTheRa** [comment]
OK. i do now have an f3 so will have to get that running. Was hoping to see in action tonight.
Any chance someone can try latest in repo - to see if the two play ball together now? Had a look at the code and it looks like it should

**Comment by u8mydog** [comment]
There is not enough memory to enable CMS but if you disabled some functionality like BARO and LED_STRIP in src/main/target/NAZE/target.h, then it will link and appears to fit in memory. Compile beta flight yourself using the command:
make TARGET=NAZE OPTIONS=CMS


-------- Original message --------From: ShikOfTheRa <notifications@github.com> Date: 2017-01-11  2:01 PM  (GMT-05:00) To: ShikOfTheRa/scarab-osd <scarab-osd@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [ShikOfTheRa/scarab-osd] Betaflight / MWOSD CMS co-existance (#364) 
Do you have to do soemthing to enable it - or is only ther ein F3 targets? Doesn't seem to obe initiation on my naze running bf 3.1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ShikOfTheRa/scarab-osd","title":"ShikOfTheRa/scarab-osd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ShikOfTheRa/scarab-osd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ShikOfTheRa in #364: Do you have to do soemthing to enable it - or is only ther ein F3 targets? Doesn't seem to obe initiation on my naze running bf 3.1"}],"action":{"name":"View Issue","url":"https://github.com/ShikOfTheRa/scarab-osd/issues/364#issuecomment-271961906"}}}

**Comment by ShikOfTheRa** [comment]
OK - did bits in post 1 - works fantastic. 
Tried all sorts of combos to get to lock / cause issues. Couldn't break it. 

@jflyper any need to retain the canvas first / * ? 
Have left it in but it seems to work great. Bit odd having different stick commands. I guess they were there because of co-existance issues. 

You did a great job on this!

**Comment by jflyper** [comment]
@ShikOfTheRa 
The upper left asterisk is to indicate that there is MSP_DISPLAYPORT message coming in without starting. Can delete it now, but leaving it might help trouble shoot some cases.

**Comment by ShikOfTheRa** [comment]
Yeah its all merged and tested. I can say it works awesome.
I also put an extra menu page in for betaflight 3.1 to access or "advertise" it, because I think it's a largely unknown feature.

really would like to see this in iNav - fantastic for easy  field tuning so have just added a note re that

**Comment by ShikOfTheRa** [comment]
Oh - no issues in leaving the * - in testing I couldn't make it occur any more. I guess that's a positive

**Comment by jflyper** [comment]
@ShikOfTheRa Awesome!!!

**Comment by ShikOfTheRa** [comment]
Think this can be closed. Feedback v positive.
