### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by OtterNas3** [ShikOfTheRa/scarab-osd#427]
As me, and i guess many others, cant figure out why Google is not accepting the Credit Card in the Chrome App-Store, is there a reason why PayPal is not accepted?

**Comment by OtterNas3** [comment]
I would donate even 5$ for the Configurator if i would be able to get it another way...

**Comment by ShikOfTheRa** [comment]
I don't know why google doesn't accept . It is a pain.
A version that can accept paypal is coming soon hope within a month

**Comment by MathijsG** [comment]
What if you use the chrome extension in for example this latest test version: https://github.com/ShikOfTheRa/scarab-osd/archive/1.7.1.1.zip

it's within the MW_OSD_GUI folder, and you can manually drag it in Chrome on the extension page of Chrome.

That's how I bypassed the paid option. Not because I don't want to pay for this beautiful project, but because Google doesn't let me. Outside the US credit cards are much less common.

**Comment by OtterNas3** [comment]
Unfortunately u can't use that GUI for the v1.7+ of the OSD Firmware

**Comment by OtterNas3** [comment]
Hey Shik,

sorry for bothering you again, but, any Update on this?

-Otter-

**Comment by ShikOfTheRa** [comment]
Its pretty close. Drop email to gary@flypix.co.uk as will need a test group soon
