### ISSUE TITLE
no data message

### ISSUE THREAD

**Issue by retif** [ShikOfTheRa/scarab-osd#498]
i have 1.8 mwosd minimosd inav plane firmware and 1.8.1 inav, connecting minimosd through softserial. and it show me message "no data". Previously i used other firmware it mostly worked, but had some glitches, so i decided to move, but it not works at all for me, i think the problem may be in port speed which is limited to 19200 for softserial, but how can i change port speed on minimosd mwosd?

**Comment by ShikOfTheRa** [comment]
Hi, port speed is fixed in pre-compiled GUI frimware
 - you need to compile and upload your own version.  

here is guide. Look in config.h for baud rate. Once changed, don't forget to change GUI baud rate to be able to talk to OSD at new rate. 
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

**Comment by retif** [comment]
thanks, it worked
