### ISSUE TITLE
Wrong current and voltage reading with aeromax osd

### ISSUE THREAD

**Issue by shro70** [ShikOfTheRa/scarab-osd#512]
Hi.

I have a problem with my aeromax osd + pitlab 75 A current meter.
The 1.8 configurator show the correct value ( 13v) but the osd show a voltage of 0.8 to 1.25v and a current which stay at 0A . I tried to play with the option in the GUI without success and when I try to change the alternate divider value in the firmware I can't compile it.

Config : 
-aeromax osd 1.8 inav aero firmware with pitlab current meter 75a .

Thanks.

**Comment by ShikOfTheRa** [comment]
Hi - please note the GUI preview is only for organising the screen - it doesn't replicate true value of OSD.

For voltage - that sensor has a divider on board. There is also one on aeromax so cant use that output. Connect 3s/4s/5s full battery voltage into the aeromax vbat pin. It is why you are seeing a low voltage - because it is already divided to a small value.

For current:
This should work.
Connect the "I" output from sensor
Make sure "Use direct connect" is enabled.
Offset = 0 to start
Adjust = 750 to start

**Comment by shro70** [comment]
Hi. It's not the GUI preview which show me the correct value but the values in the upper part of the configurator.
I have enabled "direct connection" and "5v ref" and the "adjust" setting is limited to ~256.

Thanks for you reply and sorry for my bad English.

**Comment by ShikOfTheRa** [comment]
Ah, I understand. What version are you running? I just tried the latest 1.8 and it allows me to set higher values

**Comment by shro70** [comment]
I'm using the 1.8 version. I even tested the 1.8 1 test release without success.

**Comment by ShikOfTheRa** [comment]
Hi - I can change OK - see example. Not you might have to connect to see true max values allowed.

![image](https://user-images.githubusercontent.com/11336532/40667969-4c325678-635b-11e8-8e88-5d2d254eef0c.png)

**Comment by ShikOfTheRa** [comment]
Did you find a resolution?
