### ISSUE TITLE
Throttle setting and Pitch value indicator

### ISSUE THREAD

**Issue by JeyPi** [ShikOfTheRa/scarab-osd#515]
I am using the MW configurator 1.8.0.0
PX4 + arduplane
Micro OSD v2.3

The pitch indicator uses negative numbers during climb and positive during descend. That is obviously nonsense.
The THR indicator reacts to my channel 3 while on my radio it is channel 1.
No matter what I set in the transmitter type.
Mine is mode 1
Channel 1 right stick --Up and Down THR
Channel 2 right stick -- L and R  Ailerons
Channel 3  left stick -- Up and Down Elevator
Channel 4 left stick --L and R  rudder

**Comment by ShikOfTheRa** [comment]
Pitch value:
There is no right or wrong way. Some are positive forward, other negative.Same as roll or yaw.
I would agree that pitch up  = positive is more prevelant - and code default was recently amended to reflect that. It was a setting for those that compile their own and do not flash from the gui

TX type support:
This wasn't available for ardupilot/px4 users. It is now added for testing.

You can try release 1.8.1.2 which is available if select the "show test releases" in the gui flash utility

**Comment by ShikOfTheRa** [comment]
If tick "test box" like below, should see test releases. it has changes which hopefully you need. I only uploaded this morning. Just pick latest the one.
 
![image](https://user-images.githubusercontent.com/11336532/40840196-9477db08-659d-11e8-820d-2fa72f1adf10.png)

To get correct throttle display, have to match following to how your tx is set up. Probably the middle one. This functionality wasn't enabled for px4/ardupilot in 1.8 of the OSD
![image](https://user-images.githubusercontent.com/11336532/40840315-078d323c-659e-11e8-94ac-8b78b6ca76be.png)

**Comment by ShikOfTheRa** [comment]
for pitch roll I could set defaults so that up/down are different for copter/plane - but I can't win as always someone wants it different :) probably not enough memory for it to be a gui option. 
I think up = positive for airplane and copter is best.

If you build own using arduino, these parameters can be changed as below:
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

#define INVERT_PITCH_SIGN           // Invert the sign of the displayed numeric value for the pitch angle (ex: pitch up = positive )
//#define INVERT_ROLL_SIGN          // Invert the sign of the displayed numeric value for the roll angle (ex: roll right = negative )

**Comment by JeyPi** [comment]
I was able to flash as you suggested and the pitch sign works fine for me as it is supposed to. I did not have to use Arduino to correct it. Also the THR problem solved Thanks. Closing
