### ISSUE TITLE
MinimOSD video voltage issue...

### ISSUE THREAD

**Issue by maRCnh33** [ShikOfTheRa/scarab-osd#590]
I hope you can help me!

I have the Minimosd 2.1 and all the osd information is coming from the FC, also the main battery voltage. But i cannot get the video voltage, i tried several options.... feed the osd from ftdi side with 5v and also on the other side 12v from fpv battery.... but nothing!!

So, my question is:

Do i need to set the main battery voltage "use direct connect voltage" first and THEN the bat2 port is enabled and it is getting the video voltage from there.....

So when the main battery voltage is coming from the FC then the videovoltage will never be measured from BAT2.... i think....

So,

Do i need to set the main battery voltage "use direct connect voltage" ?????????

Best regards Marc

**Comment by ShikOfTheRa** [comment]
The default operation for mavlink is to use only direct connect video voltage to OSD. I can't remember why, but there was a reason. Possibly becaus eit was most common option.
So use main battery from FC or direct to OSD board, video direct to OSD board.

There is support in the code for video voltage coming from the FC but I have never tried myself..

To do this, you have to create and flash a custom build with the following enabled :
//#define MAV_VBAT2                 // Use VBAT2 from mavlink instead of direct connect 

Instructions for building custome firmware:
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide
