### ISSUE TITLE
MicrominimOSD with Inav

### ISSUE THREAD

**Issue by MsnSazabi** [ShikOfTheRa/scarab-osd#637]
Hello,

I'm having issue running OSD with inav. OSD fw ver 1.9.2, target inav, inav fw 2.6.1. Inav port sends data in msp at 115200. Port is working, checked by reading port output. No data on osd. What am I doing wrong?

**Comment by ShikOfTheRa** [comment]
tx/rx wires crossed?

**Comment by MsnSazabi** [comment]
> tx/rx wires crossed?

nope, wired correctly.

**Comment by ShikOfTheRa** [comment]
Actually I have exact setup on one of my tricopters so it should work 

The GUI has a built in emulator with is iNav compatible - if you are able to hook up PC and use that whilt still seeing the OSD output this can be used to rule out OSD.

Usual issues are:
Not uploading correct firmware to OSD 
OSD TX connected to FC TX, OSD RX to FC RX instead of OSD TX to FC RX and OSD RX to FC TX
Baud rates not matching either side. If using iNav, use 115k
Not selecting MSP on the iNAV serial port in the iNav GUI ** easy one to miss. Catches me all the time.

Can sometimes get odd results if using Serial 1 on FC for MSP when connected to USB at same time.

Might be something in here that will help:
https://github.com/ShikOfTheRa/scarab-osd/wiki/Troubleshooting-Connectivity

**Comment by MsnSazabi** [comment]
> Actually I have exact setup on one of my tricopters so it should work
> 
> The GUI has a built in emulator with is iNav compatible - if you are able to hook up PC and use that whilt still seeing the OSD output this can be used to rule out OSD.
> 
> Usual issues are:
> Not uploading correct firmware to OSD
> OSD TX connected to FC TX, OSD RX to FC RX instead of OSD TX to FC RX and OSD RX to FC TX
> Baud rates not matching either side. If using iNav, use 115k
> Not selecting MSP on the iNAV serial port in the iNav GUI ** easy one to miss. Catches me all the time.
> 
> Can sometimes get odd results if using Serial 1 on FC for MSP when connected to USB at same time.
> 
> Might be something in here that will help:
> https://github.com/ShikOfTheRa/scarab-osd/wiki/Troubleshooting-Connectivity

Thanks. It works with msp emulation. I guess, it's something with inav than.

**Comment by ShikOfTheRa** [comment]
OK - maybe it helps a little in narrowing the fault down.

Also hardware considerations - not using an inverted serial port or possibly serial 1 issue like mentioned.

Good luck!

**Comment by MsnSazabi** [comment]
> OK - maybe it helps a little in narrowing the fault down.
> 
> Also hardware considerations - not using an inverted serial port or possibly serial 1 issue like mentioned.
> 
> Good luck!

Tanks. Btw, how to change MWOSD port speed? Just found out inav softserial is limited to 19200. And my osd is on softserial.

**Comment by ShikOfTheRa** [comment]
OK. That for sure would explain.

That requires a custom build. Follow this guide:
Settings you need to amend (remove leading // in config.h) are:
#define iNAV
#define BAUDRATE 19200
and then change GUI speed to 19200 to be able to connect

https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

**Comment by MsnSazabi** [comment]
> OK. That for sure would explain.
> 
> That requires a custom build. Follow this guide:
> Settings you need to amend (remove leading // in config.h) are:
> #define iNAV
> #define BAUDRATE 19200
> and then change GUI speed to 19200 to be able to connect
> 
> https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

Thanks!
