### ISSUE TITLE
Throttle value is 11% after arming

### ISSUE THREAD

**Issue by vgwit** [ShikOfTheRa/scarab-osd#653]
With R2.0.0.1 version throttle value on OSD right after arming is 11%, not 0. Whith stick moving up it rises.
Use LibrePilot with Revo-mini, Next code, iBus and micro minimOSD.
On R1.9.0.5 throttle started from 0.
How to make AUTOTHROTTLE work?

**Comment by ShikOfTheRa** [comment]
Hi

Sorry for very late reply. This is because autothrottle works on the lowest and highest values received. Mainly with multirotors, throttle require 8-12% throttle to spin at lowest "throttle". 

If you want to calibrate specifically for your setup, basically you have to create a custom build / hex file to upload. Link is below.

in config.h, need to correct autothrottle, OSD hardware, Flight controller and aircraft type.
https://github.com/ShikOfTheRa/scarab-osd/wiki/Custom-installation-guide

// To use comment out AUTOTHROTTLE and adjusts the maximum and minimum throttle values
#define AUTOTHROTTLE
#define HIGHTHROTTLE 1900           // Maximum recognised value for throttle
#define LOWTHROTTLE  1100           // Minimum recognised value for throttle
